### ISSUE TITLE
[BUG] after use !time console throws exceptions

### ISSUE THREAD

**Issue by jovicdev97** [K4ryuu/CS2_PlaytimeTracker#3]
**Describe the bug**
After u type a command (!time or !mytime) you will get exceptions in console.

**To Reproduce**
OS: Ubuntu 22.04
CSSharp Version used: https://github.com/roflmuffin/CounterStrikeSharp/actions/runs/6772103962
Install plugin, restart server, edit database config JSON and restart server.

Typing !time / !mytime will throw this exceptions:

**Console:**
```
L 11/06/2023 - 22:50:05: MatchStatus: Team "TERRORIST" is unset.
23:50:08
L 11/06/2023 - 22:50:05: MatchStatus: Score: 0:0 on map "jb_improSystem.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.Collections.Generic.KeyNotFoundException: The given key '0' was not present in the dictionary.
at K4ryuuPlaytimePlugin.PlaytimePlugin.SaveClientTime(CCSPlayerController player) in /Users/sples/Documents/GitHub/CS2_PlaytimeTracker/src/K4ryuuPlaytimeTracker.cs:line 156
at K4ryuuPlaytimePlugin.PlaytimePlugin.OnCommandCheckPlaytime(CCSPlayerController player, CommandInfo command) in /Users/sples/Documents/GitHub/CS2_PlaytimeTracker/src/K4ryuuPlaytimeTracker.cs:line 42
at CounterStrikeSharp.API.Core.BasePlugin.<>c__DisplayClass31_0.<AddCommand>b__0(Int32 i, IntPtr ptr) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 166
at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
--- End of inner exception stack trace ---
at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.Delegate.DynamicInvokeImpl(Object[] args)
at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 70
23:50:10
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.Collections.Generic.KeyNotFoundException: The given key '0' was not present in the dictionary.
at K4ryuuPlaytimePlugin.PlaytimePlugin.SaveClientTime(CCSPlayerController player) in /Users/sples/Documents/GitHub/CS2_PlaytimeTracker/src/K4ryuuPlaytimeTracker.cs:line 156
at K4ryuuPlaytimePlugin.PlaytimePlugin.OnCommandCheckPlaytime(CCSPlayerController player, CommandInfo command) in /Users/sples/Documents/GitHub/CS2_PlaytimeTracker/src/K4ryuuPlaytimeTracker.cs:line 42
at CounterStrikeSharp.API.Core.BasePlugin.<>c__DisplayClass31_0.<AddCommand>b__0(Int32 i, IntPtr ptr) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 166
at InvokeStub_Action`2.Invoke(Object, Object, IntPtr*)
at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
--- End of inner exception stack trace ---
at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.Delegate.DynamicInvokeImpl(Object[] args)
at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 70
23:50:14
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.Collections.Generic.KeyNotFoundException: The given key '0' was not present in the dictionary.
at K4ryuuPlaytimePlugin.PlaytimePlugin.OnClientSpawn(EventPlayerSpawn event, GameEventInfo info) in /Users/sples/Documents/GitHub/CS2_PlaytimeTracker/src/K4ryuuPlaytimeTracker.cs:line 93
at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
--- End of inner exception stack trace ---
at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.Delegate.DynamicInvokeImpl(Object[] args)
at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 70
```

**Comment by K4ryuu** [comment]
Greetings,
We have checked through the plugin for errors, but we were unable to reproduce the problem of yours.

I ask you to update your cssharp to the latest [Build & Publish](https://github.com/roflmuffin/CounterStrikeSharp/actions/workflows/cmake-single-platform.yml) version and the latest Playtime Tracker version.

After that please let me know whether or not that fixed your issue.

Best Regards,
K4ryuu

**Comment by K4ryuu** [comment]
Greetings,
The problem has been solved within the https://github.com/K4ryuu/CS2_PlaytimeTracker/commit/17987b6086d37e14b4328ad335cccb2abdd50f91 commit. Please update the plugin from the releases to the last version.

Thank you for your patience!

Best Regards,
K4ryuu
