### ISSUE TITLE
Error with new version

### ISSUE THREAD

**Issue by MinnDe** [K4ryuu/CS2_PlaytimeTracker#4]
**The plugin stopped working after the update.**

```
at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.Delegate.DynamicInvokeImpl(Object[] args)
at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 81
SteamNetworkingSockets lock held for 5.7ms.  (Performance warning.)  ServiceThread
This is usually a symptom of a general performance problem such as thread starvation.
"MinnDe<0><[U:1:756741]><TERRORIST>" OnPreResetRound => CTMDBG, team 2  will switch 0 117.39
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.Collections.Generic.KeyNotFoundException: The given key '0' was not present in the dictionary.
at K4ryuuPlaytimePlugin.PlaytimePlugin.OnClientSpawn(EventPlayerSpawn event, GameEventInfo info) in /Users/sples/Documents/GitHub/CS2_PlaytimeTracker/src/K4ryuuPlaytimeTracker.cs:line 95
at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by K4ryuu** [comment]
Update your CSSharp to latest version.... As you see in changes at the release it was updated to the today's last build.

**Comment by MinnDe** [comment]
CSSharp is the latest version...

**Comment by K4ryuu** [comment]
I am going to check on it then shortly, and I will keep you updated.
Thanks for the feedback!

**Comment by K4ryuu** [comment]
Greetings,
The problem has been solved within the https://github.com/K4ryuu/CS2_PlaytimeTracker/commit/17987b6086d37e14b4328ad335cccb2abdd50f91 commit. Please update the plugin from the releases to the last version.

Thank you for your patience!

Best Regards,
K4ryuu
